name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main # 當你推送到 main 分支時觸發自動部署

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 支援 Sass/SCSS 編譯，確保樣式不漏勾

      - name: Build
        run: hugo --gc --minify # 這裡預設「絕對不會」把草稿打包進去

      - name: Deploy to Public Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: ppdiary/ppdiary.github.io
          publish_dir: ./public
          publish_branch: main